BooksDevotee/Models/Basket.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace BooksDevotee.Models
{
    public enum BasketStatus
    {
        [Display(Name = "Aktywne")]
        Active = 0,

        [Display(Name = "Anulowane")]
        Canceled = 1,

        [Display(Name = "W transakcji")]
        InTransaction = 2,

        [Display(Name = "Opłacone")]
        Paid = 3,

        [Display(Name = "Wysłane")]
        Sent = 4,

        [Display(Name = "Spakowane")]
        Prepared = 5
    }

    public class Basket
    {
        public int BasketId { get; set; }
        public string ApplicationUserId { get; set; }
        public BasketStatus Status { get; set; }
        public DateTime CreationDate { get; set; }
        public DateTime? PaymentDate { get; set; }
        public DateTime? SentDate { get; set; }
        public DateTime? PreparedDate { get; set; }
        public DateTime? CancelDate { get; set; }

        public ICollection<BasketBook> BasketBooks { get; set; }
        public ApplicationUser ApplicationUser { get; set; }
    }
}

BooksDevotee/ViewModels/Basket/ShowViewModel.cs
namespace BooksDevotee.ViewModels.Basket
{
    public class ShowViewModel
    {
        public Models.Basket ActiveBasket { get; set; }
    }
}

BooksDevotee/Controllers/BasketController.cs
using BooksDevotee.Models;
using BooksDevotee.Repositories;
using BooksDevotee.Utils;
using BooksDevotee.ViewModels.Basket;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Security.Claims;
using System.Threading.Tasks;

namespace BooksDevotee.Controllers
{
	[Authorize]
	public class BasketController : Controller
	{
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IBasketRepository basketRepository;

        public BasketController(UserManager<ApplicationUser> userManager, IBasketRepository basketRepository)
		{
            this.userManager = userManager;
            this.basketRepository = basketRepository;
        }

		public async Task<IActionResult> ShowAsync()
		{
			//ToDo koszyk jest pusty
			ApplicationUser applicationUser = await userManager.GetUserAsync(User);
			Basket basket = BasketUtils.GetOrCreateActiveBasket(basketRepository, applicationUser);

			ShowViewModel viewModel = new ShowViewModel()
			{
				ActiveBasket = basketRepository.GetBasketDataById(basket.BasketId)
			};

			return View(viewModel);
		}

		public async Task<IActionResult> AddOneBookAsync(int bookId)
		{
			ApplicationUser applicationUser = await userManager.GetUserAsync(User);
			Basket basket = BasketUtils.GetOrCreateActiveBasket(basketRepository, applicationUser);

			BasketBook basketBook = basketRepository.GetBasketBook(basket.BasketId, bookId);
			if (basketBook == null)
            {
				basketBook = new BasketBook()
				{
					BasketId = basket.BasketId,
					BookId = bookId,
					Quantity = 1
				};
				basketRepository.AddBasketBook(basketBook);
            }
            else
            {
				basketBook.Quantity++;
				basketRepository.UpdateBasketBook(basketBook);
			}

			return RedirectToAction("show");
		}

		public async Task<IActionResult> RemoveOneBookAsync(int bookId)
		{
			ApplicationUser applicationUser = await userManager.GetUserAsync(User);
			Basket basket = BasketUtils.GetOrCreateActiveBasket(basketRepository, applicationUser);

			BasketBook basketBook = basketRepository.GetBasketBook(basket.BasketId, bookId);
			if (basketBook != null && basketBook.Quantity > 0)
			{
				basketBook.Quantity--;

				if (basketBook.Quantity > 0)
					basketRepository.UpdateBasketBook(basketBook);
				else
					basketRepository.DeleteBasketBook(basketBook.BasketId, basketBook.BookId);
			}

			return RedirectToAction("show");
		}

		public async Task<IActionResult> RemoveAllBook(int bookId)
		{
			ApplicationUser applicationUser = await userManager.GetUserAsync(User);
			Basket basket = BasketUtils.GetOrCreateActiveBasket(basketRepository, applicationUser);

			BasketBook basketBook = basketRepository.GetBasketBook(basket.BasketId, bookId);
			if (basketBook != null && basketBook.Quantity > 0)
			{
				basketRepository.DeleteBasketBook(basketBook.BasketId, basketBook.BookId);
			}

			return RedirectToAction("show");
		}
	}
}

BooksDevotee/Views/Basket/Show.cshtml
@model BooksDevotee.ViewModels.Basket.ShowViewModel

@{
    ViewBag.Title = "Zawartość koszyka";
    Basket basket = Model.ActiveBasket;
}

<h1>Zawartość koszyka</h1>

<div class="row">
    <div class="offset-md-2 col-md-4">
        <h4 class="font-weight-bold">Tytuł</h4>
    </div>
    <div class="col-md-2">
        <h4 class="font-weight-bold">Ilość</h4>
    </div>
    <div class="col-md-2">
        <h4 class="font-weight-bold">Cena</h4>
    </div>
</div>

@{
    decimal sum = 0;
}

@foreach (BasketBook basketBook in basket.BasketBooks)
{
    <div class="row">
        <div class="col-md-2">
            @{
                Book book = basketBook.Book;
                string imgSource = Image.GetImageSource(book.Image);
            }
            <img class="card-img-top p-2" src="@imgSource" />
        </div>
        <div class="col-md-4">
            <a asp-action="details" asp-controller="home" asp-route-bookId="@book.BookId" class="text-dark">
                <h4>@book.Title</h4>
            </a>
        </div>
        <div class="col-md-2">
            <a asp-controller="Basket" asp-action="RemoveOneBook" asp-route-bookId="@book.BookId" class="btn btn-danger">
                <span class="glyphicon glyphicon-minus"></span>
            </a>

            <h4 class="m-3" style="display:inline">@basketBook.Quantity</h4>

            <a asp-controller="Basket" asp-action="AddOneBook" asp-route-bookId="@book.BookId" class="btn btn-success">
                <span class="glyphicon glyphicon-plus"></span>
            </a>
        </div>
        <div class="col-md-2">
            @{
                decimal price = book.Price * basketBook.Quantity;
                sum += price;
            }
            <h4>@price zł</h4>
        </div>
        <div class="col-md-2">
            <a asp-controller="Basket" asp-action="RemoveAllBook" asp-route-bookId="@book.BookId" class="btn btn-danger">
                <span class="glyphicon glyphicon-remove"></span>
            </a>
        </div>
    </div>
}

<div class="row">
    <div class="offset-md-8 col-md-3">
        <h4>@sum zł</h4>
    </div>
</div>

<div class="row">
    <div class="col-md-4">
        <h4 class="font-weight-bold">Wybierz metodę płatności</h4>
    </div>
</div>

<div class="row mt-md-3">
    <div class="col-md-2 w-100">
        <a asp-controller="payu" asp-action="createOrder" class="btn btn-primary btn-block" role="button">
            PayU
        </a>
    </div>
</div>